### ISSUE TITLE
delete update where 1=1 not work

### ISSUE THREAD

**Issue by se7enshidb** [eradman/pg-safeupdate#1]
postgres=# update t_sales set prod='c';
ERROR:  UPDATE requires a WHERE clause
postgres=# update t_sales set prod='c' where 1=1;
UPDATE 6
postgres=# delete from t_sales ;
ERROR:  DELETE requires a WHERE clause
postgres=# update t_sales set prod='c';
ERROR:  UPDATE requires a WHERE clause
postgres=# update t_sales set prod='c' where 1=1;
UPDATE 6
postgres=# delete from t_sales where 1=1;
DELETE 6

**Comment by eradman** [comment]
The examples you provided appear to work. Which result is incorrect?
