### ISSUE TITLE
How to enable safeupdate per db?

### ISSUE THREAD

**Issue by steve-chavez** [eradman/pg-safeupdate#2]
Removed `shared_preload_libraries=safeupdate` because one particular application(https://traccar.org/) needs a delete without where.

So now I tried `alter database mydb set safeupdate.enabled=1` with no luck.

**Comment by eradman** [comment]
Hi, the `safeupdate` extension cannot be disabled per database, but I can see this being useful. I'll look into a solution.

**Comment by eradman** [comment]
Actually, it seems that nothing special is required of an extension to use per user or per database GUCs. I verified that this works

```
$ url=$(pg_tmp -o "-c shared_preload_libraries=safeupdate")
$ psql $url
test=# alter database test set safeupdate.enabled=off;
test=# CREATE TABLE abc();
test=# \q
```

Now when I reconnect I can verify that it is off, and that that no where clause is required

```
$ psql $url
test=# SHOW safeupdate.enabled;
 safeupdate.enabled
--------------------
 off
(1 row)

test=# DELETE FROM abc;
DELETE 0
```

**Comment by steve-chavez** [comment]
@eradman Thank you, that works!

I was trying the opposite direction. Would be good to add this use case to the README.

Thanks again! Closing...

**Comment by steve-chavez** [comment]
I've also noted that it's possible to enable this per user with [session_preload_libraries](https://www.postgresql.org/docs/11/runtime-config-client.html#GUC-SESSION-PRELOAD-LIBRARIES):
```sql
alter role my_user set session_preload_libraries = 'safeupdate';
```

**Comment by steve-chavez** [comment]
Just in case, `session_preload_libraries` also works on a database:
```sql
alter database mydb set session_preload_libraries = 'safeupdate';
```

**Comment by eradman** [comment]
@steve-chavez excellent observation! I added this example to the README
