### ISSUE TITLE
Support for PostgreSQL 16

### ISSUE THREAD

**Issue by steve-chavez** [eradman/pg-safeupdate#7]
Hi @eradman,

We're getting an error with pg-safeupdate on PG 16: https://github.com/PostgREST/postgrest/pull/2958#issuecomment-1734279783

I was wondering if you've tested on pg 16?

Weird thing is that the above only fails on MacOS.

**Comment by eradman** [comment]
I have tested this lightly on 16 on OpenBSD:

```
$ pg_tmp -o "-c shared_preload_libraries=$PWD/safeupdate"
postgresql:///test?host=%2Ftmp%2Fephemeralpg.heQKIk
$ psql postgresql:///test?host=%2Ftmp%2Fephemeralpg.heQKIk
Output format is wrapped.
psql (16.0)
Type "help" for help.

test=# CREATE TABLE abc (id int);
CREATE TABLE
test=# DELETE FROM abc;
ERROR:  DELETE requires a WHERE clause
```
What is the failure you're seeing?

Also try running `make test` to see if the pg-safeupdate tests pass

**Comment by steve-chavez** [comment]
Thanks for confirming. It works fine on Linux/pg16 as well.

I'll close for now since I'm not sure if it's a MacOS issue or an issue with Nix the package manager.
